// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  kmdoSidebar: [
    {
      type: 'category',
      label: '快速开始',
      collapsible: true,
      collapsed: true,
      "link": {
        "type": "generated-index",
        "title": "快速开始",
        "slug": "/quick-start"
      },
      items: [
        'start/install'
      ],
    },
    {
      type: 'category',
      label: '命令行',
      collapsible: true,
      collapsed: true,
      "link": {
        "type": "generated-index",
        "title": "命令行",
        "slug": "/cmd"
      },
      items: [
        'cmd/env',
        'cmd/pkg1',
        'cmd/history',
        'cmd/tree',
        'cmd/version',
        {
          type: 'category',
          label: 'mirror 命令',
          collapsible: true,
          collapsed: true,
          "link": {
            "type": "generated-index",
            "title": "mirror",
            "slug": "/cmd/mirror"
          },
          items: [
            'cmd/mirror',
            'cmd/mirror/init',
            'cmd/mirror/set',
            'cmd/mirror/show',
            'cmd/mirror/status',
            'cmd/mirror/index',
            'cmd/mirror/list',
            'cmd/mirror/publish',
            'cmd/mirror/baseline',
            'cmd/mirror/tag',
            'cmd/mirror/pull',
            'cmd/mirror/push',
            'cmd/mirror/merge',
            'cmd/mirror/clone'
          ],
        },
        {
          type: 'category',
          label: 'pkg 命令',
          collapsible: true,
          collapsed: true,
          "link": {
            "type": "generated-index",
            "title": "pkg",
            "slug": "/cmd/pkg"
          },
          items: [
            'cmd/pkg/init',
            'cmd/pkg/config',
            'cmd/pkg/build',
            'cmd/pkg/release',
            'cmd/pkg/mcp',
            'cmd/pkg/check',
            'cmd/pkg/healthcheck'
          ],
        }
      ],
    }

  ]
};

export default sidebars;
